### ISSUE TITLE
The ToC will prevent source code blocks from being visible

### ISSUE THREAD

**Issue by davorb** [ptpt/org-notes-style#3]
It's pretty obvious in this screenshot:

![example](https://cloud.githubusercontent.com/assets/798427/18205513/a749aa3e-7122-11e6-8f50-8c33ce40111d.png)

**Comment by ptpt** [comment]
The latest commits should get this issue fixed. I added a small left margin to ToC and also set codeblock's overflow to auto.

Thanks for reporting.

![image](https://cloud.githubusercontent.com/assets/87357/18249064/578f9f7e-737c-11e6-8820-9ef2f1d64860.png)
