### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by alhassy** [ptpt/org-notes-style#4]
I love the style; thank-you.

Your instructions do not work for me: In particular, linking to the css loads nothing.

However, I've copied your css and linking to that one works.
The copy is here: https://alhassy.github.io/next-700-module-systems/prototype/org-notes-style.css

Perhaps there is something with the URL on your end?

**Comment by ptpt** [comment]
Thanks. It's because it used http instead of https. Fixed in ea57be964d3ce3f8cad67251aed89981279a437a. All links are https now.
