### ISSUE TITLE
MathJax \ref's are not displayed

### ISSUE THREAD

**Issue by alhassy** [ptpt/org-notes-style#5]
If you try to reference an equation with MathJax's `\ref{...}`, then `org-notes-style` will not display it. The issue seems to be the styling of the anchors; removing the `a {...}` styling fixed the issue for me.

**Comment by ptpt** [comment]
@alhassy could you provide an example in org-mode, and any screenshot?

**Comment by alhassy** [comment]
I can no longer reproduce the error.

It's a wonderful style; thank-you :-)
